= Simpic

Simpic is a simple picture hosting service, effectively a slimmed down and self-hosted alternative to Google Photos.

== Feature status

Simpic is currently pre-MVP. Unless you want to help develop it, there's probably not much here for you yet.
You can see planned features in the https://github.com/csmith/simpic/issues[issue tracker].

== Running

The simplest and easiest approach to running Simpic is to use Docker. You can use the example
docker-compose.yml file in this repository to quickly build footnote:[Eventually Simpic will
be published to Docker Hub and you'll be able to pull the image from there instead of
building yourself.] and start an instance of Simpic alongside its own Postgres server.

Assuming you have https://docs.docker.com/install/[installed docker]
and https://docs.docker.com/compose/install/[docker-compose], all you need to do is:

----
docker-compose up -d
----

And then Simpic will be accessible on port 8080.

=== Configuration

Simpic is configured using either command line arguments or, preferably, environment variables.
It currently has the following options:

[%header,cols="m,m,3"]
|===
|CLI arg|Env var|Description

| -auth-key-auto-create
| SIMPIC_AUTH_KEY_AUTO_CREATE
| Whether to attempt to create a new key to sign authentication tokens if one doesn't exist. Defaults to `true`.

| -auth-key-file
| SIMPIC_AUTH_KEY_FILE
| Path to the X509-marshalled ES256 key to use to sign authentication tokens. Defaults to `data/auth.key`.

| -auth-token-expiry
| SIMPIC_AUTH_TOKEN_EXPIRY
| Length of time that authentication tokens are valid for (i.e., how long users stay logged in). Specified in
  hours/minutes/etc, e.g. "3h30m". Defaults to "744h", i.e. 31 days.

| -create-admin-password
| SIMPIC_CREATE_ADMIN_PASSWORD
.2+^.^| If both are specified, a new admin account with those credentials will be created.

| -create-admin-username
| SIMPIC_CREATE_ADMIN_USERNAME


| -dsn
| SIMPIC_DNS
| The 'data source name' to use to connect to the Postgres database. See:
  https://pkg.go.dev/github.com/lib/pq?tab=doc#hdr-Connection_String_Parameters[list of all valid parameters].

| -frontend
| SIMPIC_FRONTEND
| File system path to serve the compiled frontend files from. Defaults to `dist`.

| -migrations
| SIMPIC_MIGRATIONS
| File system path to the database migration files. Defaults to `migrations`.

| -path
| SIMPIC_PATH
| File system path to store image and thumbnail data. Defaults to `data`.

| -picture-key
| SIMPIC_PICTURE_KEY
| Key to use to generate private URLs ofr pictures. Must be 32 bytes, provided as a 64-char hexadecimal string.
If the picture key is not provided or is invalid, a random key will be generated which will mean picture
URLs will change whenever the service restarts. Use `openssl rand -hex 32` to generate.

| -port
| SIMPIC_PORT
| TCP port to listen on for requests. Defaults to 8080.
|===

== Developing

The docker-compose.dev.yml file in this repository contains a simple postgres service
that is exposed on localhost:5432, and a service to live rebuild the JavaScript frontend
that exposes a websocket endpoint on localhost:8081.

With these two running, you can run Simpic as a normal Go binary with the following env
var to use the local postgres server:

----
SIMPIC_DSN=user=simpic dbname=simpic password=nWK9aY9gkh sslmode=disable
----

The frontend will then automatically rebuild and reload in response to changes to the
source.

== Contributing

Contributions are welcome!

There is a https://pre-commit.com/[pre-commit] to go fmt and run basic checks on
commit; to enable it simply:

    pip install pre-commit
    pre-commit install
